name: Build and release for major platforms

on:
  push:
    tags: ["gh-actions"]

jobs:
  build:
    name: Upload distribution for ${{ matrix.config.fancy-name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: release-linux
            fancy-name: Linux
            os: ubuntu-latest
            bin-ext: ""
          - name: release-windows
            fancy-name: Windows
            os: windows-latest
            bin-ext: .exe
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Restore dependencies cache
        uses: actions/cache/restore@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Build
        run: |
          cargo fetch --locked
          cargo build --release
      - name: Save dependencies cache
        uses: actions/cache/save@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Rename binary artifact
        run: |
          cp target/release/sanity${{ matrix.config.bin-ext }} sanity-${{ matrix.config.name }}${{ matrix.config.bin-ext }}
      - name: Release binary
        uses: softprops/action-gh-release@v2
        with:
          files: sanity-${{ matrix.config.name }}${{ matrix.config.bin-ext }}
