name: Build and release for major platforms

on:
  push:
    tags: [gh-actions]

concurrency:
  cancel-in-progress: true
  group: ${{ github.ref_name }}

jobs:
  build:
    name: Upload distribution for ${{ matrix.cfg.fancy-name }}
    runs-on: ${{ matrix.cfg.os }}
    permissions:
      contents: write
    strategy:
      fail-fast: true
      matrix:
        cfg:
          - name: release-linux
            fancy-name: Linux
            os: ubuntu-24.04
            bin-ext: ""
          - name: release-windows
            fancy-name: Windows
            os: windows-2022
            bin-ext: .exe
    env:
      OUTPATH: sanity-${{ matrix.cfg.name }}${{ matrix.cfg.bin-ext }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-
      - name: Build
        run: cargo fetch --locked && cargo build --release
      - name: Rename binary artifact
        run: cp target/release/sanity${{ matrix.cfg.bin-ext }} ${{ env.OUTPATH }}
      - name: Release binary
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.OUTPATH }}
