name: Build and release for major platforms

on:
  push:
    tags: [gh-actions]

jobs:
  build:
    name: Upload distribution for ${{ matrix.cfg.fancy-name }}
    runs-on: ${{ matrix.cfg.os }}
    permissions:
      contents: write
    strategy:
      matrix:
        cfg:
          - name: release-linux
            fancy-name: Linux
            os: ubuntu-24.04
            bin-ext: ""
          - name: release-windows
            fancy-name: Windows
            os: windows-2022
            bin-ext: .exe
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Build
        run: cargo fetch --locked && cargo build --release
      - name: Rename binary artifact
        run: cp target/release/sanity${{ matrix.cfg.bin-ext }} sanity-${{ matrix.cfg.name }}${{ matrix.cfg.bin-ext }}
      - name: Release binary
        uses: softprops/action-gh-release@v2
        with:
          files: sanity-${{ matrix.cfg.name }}${{ matrix.cfg.bin-ext }}
